/*
 * testswgapaffinitymatrices.hpp
 *
 *  Created on: Dec 29, 2024
 *      Author: pjarnot
 */

#ifndef NSC_SEARCH_INCLUDE_TESTS_ALIGNMENT_SW_TESTSWGAPAFFINITYMATRICES_HPP_
#define NSC_SEARCH_INCLUDE_TESTS_ALIGNMENT_SW_TESTSWGAPAFFINITYMATRICES_HPP_





#endif /* NSC_SEARCH_INCLUDE_TESTS_ALIGNMENT_SW_TESTSWGAPAFFINITYMATRICES_HPP_ */
